version: '3.7'
services:
  django:
    &django
    container_name: django
    restart: always
    build: ./
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - './:/backend'
      - './cronjob:/etc/cron.d'
    env_file:
      - ./.env
    entrypoint: ./entrypoint_django.sh
    networks:
      - nginx_proxy
  bot:
    <<: *django
    container_name: bot
    depends_on:
      - django
    ports: []
    entrypoint: ./entrypoint_bot.sh
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/django/static
      - ./media:/django/media
      - ./run:/socks
    env_file:
      - .env
    networks:
      - nginx_proxy
    depends_on:
      - django
      - bot
networks:
  nginx_proxy:
    name: nginx_proxy

